# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 09:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(verbose_name='Channel')),
                ('type_data', models.CharField(max_length=255, verbose_name='Type')),
                ('value', models.FloatField(verbose_name='Value')),
                ('acquired_on', models.DateTimeField(verbose_name='Acquired On')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Home')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('radius', models.IntegerField(verbose_name='Radius')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=255, unique=True, verbose_name='Device ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('expired_on', models.DateTimeField(verbose_name='Expired On')),
                ('module_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModulePostLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_data', models.CharField(max_length=255, verbose_name='Type')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('associated', models.BooleanField(default=False, verbose_name='Associated')),
                ('module_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracking.Module')),
            ],
        ),
        migrations.AddField(
            model_name='channellog',
            name='module_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='tracking.ModulePostLog'),
        ),
    ]
