# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channellog',
            old_name='acquired_on',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='channellog',
            old_name='type_data',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='modulelocation',
            old_name='module_data',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='modulepostlog',
            old_name='created_on',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='modulepostlog',
            old_name='module_data',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='modulepostlog',
            old_name='type_data',
            new_name='type',
        ),
    ]
