# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20171031_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelocation',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Expired'),
        ),
        migrations.AlterField(
            model_name='modulelocation',
            name='expired_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expired On'),
        ),
    ]
