# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20171103_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Module'),
        ),
    ]
