# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_home_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='tracking.Module'),
        ),
    ]
