# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20171105_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'OUT'), (1, 'IN')], default=2, verbose_name='State')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP Status')),
                ('status', models.IntegerField(choices=[(0, 'SUCCESS'), (1, 'FAIL'), (2, 'RUNNING')], default=2, verbose_name='is Success')),
                ('home', models.CharField(max_length=255, verbose_name='Home')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Notified at')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='Test User', max_length=255, verbose_name='Device User'),
        ),
        migrations.AddField(
            model_name='modulelocation',
            name='state',
            field=models.IntegerField(choices=[(0, 'UP'), (1, 'DOWN')], default=0, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tracking.Module'),
        ),
    ]
