# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20171107_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelocation',
            name='is_knocked_down',
            field=models.IntegerField(choices=[(0, 'UP'), (1, 'DOWN')], default=0, verbose_name='Is knocked down'),
        ),
        migrations.AlterField(
            model_name='modulelocation',
            name='state',
            field=models.IntegerField(choices=[(0, 'IN'), (1, 'OUT')], default=0, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='state',
            field=models.IntegerField(choices=[(0, 'IN'), (1, 'OUT')], default=2, verbose_name='State'),
        ),
    ]
